### ISSUE TITLE
Debug Assertion Failed

### ISSUE THREAD

**Issue by bentinata** [rsegecin/WLStream#1]
This happen with `Publshed` branch binary, and with manual build. 

```
File: minkernel\crts\ucrt\appcrt\string\wcsicmp.cpp
Line: 86
Expression: src != nullptr
```

Release build would just stopped working.

**Comment by rsegecin** [comment]
In what Windows version have you tried to run the WLStream? I'm running on Windows 8.1 and haven't tried in others.

**Comment by rsegecin** [comment]
Try adding the line bellow on "common.h" file.

`#include <wchar.h>`

**Comment by bentinata** [comment]
I'm using Windows 10 build 15063.

Adding `#include <wchar.h>` doesn't help.
Sorry for lack of details, original error is caused by running `WLStream --device`. Variable `szLongName` at `prefs.cpp:318` have NULL value.

Just running `WLStream` produce:
```
S t o p p i n g   c a p t u r e . . .
 R e c e i v e d   s t o p   e v e n t   a f t e r   0   p a s s e s   a n d
 0   f r a m e s
 E r r o r :   m m i o C l o s e   f a i l e d :   M M S Y S E R R   =   5
```

**Comment by rsegecin** [comment]
By running `WLStream --device` you should add as well the device's name that you want to stream. You can  run just `WLStream` and it'll get the default output device or you need to run `WLStream --lsdev` first to see the available outputs and then select it with device arg like `WLStream.exe --device "Speakers(Realtek High Definition Audio)"`. Although certainly I've should predicted someone entering no parameter to some argument and given a properly output error, so I'll check it out later and change it. Thank you.

**Comment by bentinata** [comment]
Ok thanks. I'll just close the issue. I thought `--device` and `--lsdev` do the same thing.

**Comment by rsegecin** [comment]
Bentinata, In the end were you able to stream the Audio with WLStream?
